package com.ghostatlas.homeward;

import android.content.Context;
import android.graphics.*;
import android.os.VibrationEffect;
import android.os.Vibrator;
import android.view.MotionEvent;
import android.view.View;
import java.util.ArrayList;
import java.util.Random;

public final class GameView extends View implements Runnable {
    private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG), text=new Paint(Paint.ANTI_ALIAS_FLAG), stroke=new Paint(Paint.ANTI_ALIAS_FLAG);
    private final GameCore core=new GameCore(); private final WorldModel world=new WorldModel(); private final Random rng=new Random(5050);
    private final ArrayList<Spark> sparks=new ArrayList<>(); private final Vibrator vib;
    private volatile boolean running=true; private Thread loop;
    private float sw,sh,scale=1f,viewW=1600,cam,px=GameCore.START_X,py=600,sx,sy,msgT,akhet,rainbow; private int stickId=-1,hamsa=0;
    private boolean title=true,alchemy=false,bag=false,won=false; private String speaker="",message="";
    static final class Spark{float x,y,vx,vy,t,r;int c;Spark(float x,float y,float vx,float vy,float t,float r,int c){this.x=x;this.y=y;this.vx=vx;this.vy=vy;this.t=t;this.r=r;this.c=c;}}

    public GameView(Context c){super(c);vib=(Vibrator)c.getSystemService(Context.VIBRATOR_SERVICE);text.setTypeface(Typeface.create("sans-serif-condensed",Typeface.BOLD));stroke.setStyle(Paint.Style.STROKE);stroke.setStrokeWidth(3);setKeepScreenOn(true);}
    @Override protected void onAttachedToWindow(){super.onAttachedToWindow();loop=new Thread(this,"homeward");loop.start();}
    @Override protected void onDetachedFromWindow(){running=false;if(loop!=null)loop.interrupt();super.onDetachedFromWindow();}
    @Override protected void onSizeChanged(int w,int h,int ow,int oh){sw=w;sh=h;scale=Math.max(.4f,sh/900f);viewW=sw/scale;}
    @Override public void run(){long last=System.nanoTime();while(running){long now=System.nanoTime();float dt=Math.min(.033f,(now-last)/1_000_000_000f);last=now;if(!title&&!won&&!alchemy&&!bag)update(dt);postInvalidate();try{Thread.sleep(16);}catch(Exception ignored){}}}
    private void update(float dt){msgT=Math.max(0,msgT-dt);akhet=Math.max(0,akhet-dt);rainbow=Math.max(0,rainbow-dt);float m=(float)Math.sqrt(sx*sx+sy*sy);if(m>.08f){float nx=sx/Math.max(1,m),ny=sy/Math.max(1,m),speed=310*(rainbow>0?1.65f:1);px=core.constrainX(px,px+nx*speed*dt);py=Math.max(220,Math.min(790,py+ny*speed*dt));}cam=Math.max(0,Math.min(GameCore.WORLD_W-viewW,px-viewW*.32f));if(rainbow>0&&rng.nextFloat()<.45f)spawn(px,py-45,randColor(),2);for(int i=sparks.size()-1;i>=0;i--){Spark s=sparks.get(i);s.x+=s.vx*dt;s.y+=s.vy*dt;s.t-=dt;if(s.t<=0)sparks.remove(i);}}

    @Override protected void onDraw(Canvas c){if(title){drawTitle(c);return;}c.save();c.scale(scale,scale);drawWorld(c);c.restore();drawHud(c);if(msgT>0)drawMessage(c);if(alchemy)drawAlchemy(c);if(bag)drawBag(c);if(won)drawWin(c);}
    private void drawTitle(Canvas c){c.drawColor(Color.rgb(4,9,25));for(int i=0;i<110;i++){p.setColor(Color.rgb(80+(i*9)%150,110+(i*13)%130,150+(i*7)%100));c.drawCircle((i*97)%Math.max(1,(int)sw),(i*53)%Math.max(1,(int)(sh*.62)),1+i%3,p);}text.setTextAlign(Paint.Align.CENTER);text.setColor(0xffffdd78);text.setTextSize(Math.min(60,sw*.065f));c.drawText("NEW ATLANTIS: HOMEWARD",sw/2,sh*.28f,text);text.setColor(0xff8ff5e7);text.setTextSize(Math.min(20,sw*.022f));c.drawText("GHOST ATLAS • NHCM 5.0 • ATLANTEAN ARCADE 01",sw/2,sh*.37f,text);text.setColor(Color.WHITE);text.setTextSize(Math.min(21,sw*.024f));c.drawText("FORAGE • GATHER • ALCHEMIZE • MEET THE WIZARDS • GET HOME",sw/2,sh*.49f,text);p.setColor(0xff167985);c.drawRoundRect(sw*.34f,sh*.62f,sw*.66f,sh*.78f,26,26,p);text.setTextSize(Math.min(23,sw*.026f));c.drawText("BEGIN THE ROAD HOME",sw/2,sh*.72f,text);}
    private void drawWorld(Canvas c){LinearGradient g=new LinearGradient(0,0,0,900,new int[]{0xff100e3b,0xff16566b,0xff149384},null,Shader.TileMode.CLAMP);p.setShader(g);c.drawRect(0,0,viewW,900,p);p.setShader(null);for(int i=0;i<30;i++){float x=180+i*260;if(x<cam-100||x>cam+viewW+100)continue;float h=120+(i%5)*42;p.setColor(0xaa164b60);c.drawRect(x-cam-35,620-h,x-cam+35,620,p);p.setColor(0xff6be8dd);c.drawRect(x-cam-4,620-h-28,x-cam+4,620-h+8,p);}p.setColor(0xff276b59);c.drawRect(0,620,viewW,900,p);p.setColor(0xaa52dfe8);Path river=new Path();river.moveTo(0,744);for(int x=0;x<=viewW;x+=70)river.lineTo(x,738+(float)Math.sin((x+cam)*.007)*18);river.lineTo(viewW,835);river.lineTo(0,835);river.close();c.drawPath(river,p);drawResources(c);drawCauldrons(c);drawWizards(c);drawBridges(c);drawHome(c);drawPlayer(c);for(Spark s:sparks){if(s.x>cam-80&&s.x<cam+viewW+80){p.setColor(s.c);c.drawCircle(s.x-cam,s.y,s.r,p);}}}
    private void drawResources(Canvas c){for(WorldModel.ResourceNode n:world.resources){if(n.gathered)continue;float x=n.x-cam;if(x<-70||x>viewW+70)continue;int col=ingredientColor(n.type);p.setColor(Color.argb(70,Color.red(col),Color.green(col),Color.blue(col)));c.drawCircle(x,n.y,akhet>0?44:30,p);p.setColor(col);c.drawCircle(x,n.y,12,p);stroke.setColor(Color.WHITE);c.drawCircle(x,n.y,19,stroke);text.setTextAlign(Paint.Align.CENTER);text.setTextSize(13);text.setColor(Color.WHITE);c.drawText(Inventory.NAMES[n.type],x,n.y-31,text);}}
    private void drawCauldrons(Canvas c){for(WorldModel.Cauldron q:world.cauldrons){float x=q.x-cam;if(x<-80||x>viewW+80)continue;p.setColor(0xff342447);c.drawOval(x-46,q.y-20,x+46,q.y+27,p);p.setColor(0xff70efd9);c.drawOval(x-34,q.y-15,x+34,q.y+6,p);for(int i=0;i<5;i++){p.setColor(randColor());c.drawCircle(x-18+i*9,q.y-31-(i%2)*7,4,p);}text.setTextAlign(Paint.Align.CENTER);text.setTextSize(13);text.setColor(0xffffd968);c.drawText("ALCHEMY",x,q.y+53,text);}}
    private void drawWizards(Canvas c){for(WorldModel.WizardNode w:world.wizards){float x=w.x-cam;if(x<-110||x>viewW+110)continue;int[] robes={0xffd2a64e,0xff4a2a78,0xffe5ddb0,0xff914cb0,0xff2ea6bc};p.setColor(Color.argb(65,255,230,135));c.drawCircle(x,w.y-62,75,p);p.setColor(robes[w.index]);Path robe=new Path();robe.moveTo(x,w.y-85);robe.lineTo(x-40,w.y+38);robe.lineTo(x+40,w.y+38);robe.close();c.drawPath(robe,p);p.setColor(0xffd8ad82);c.drawCircle(x,w.y-102,24,p);p.setColor(w.index==1?0xff181525:0xfff0daa2);Path hat=new Path();hat.moveTo(x,w.y-164);hat.lineTo(x-38,w.y-121);hat.lineTo(x+38,w.y-121);hat.close();c.drawPath(hat,p);stroke.setColor(Color.WHITE);c.drawLine(x+30,w.y-50,x+56,w.y+28,stroke);p.setColor(0xff8cfff1);c.drawCircle(x+30,w.y-52,8,p);text.setTextAlign(Paint.Align.CENTER);text.setTextSize(13);text.setColor(Color.WHITE);c.drawText(w.name,x,w.y+60,text);}}
    private void drawBridges(Canvas c){float[] b={1720,3040,4300,5520};for(int i=0;i<4;i++){float x=b[i]-cam;if(x<-60||x>viewW+60)continue;boolean open=core.isWizardMet(i);p.setColor(open?0x99ffdd75:0xbb233a55);c.drawRoundRect(x-18,515,x+18,810,14,14,p);text.setTextAlign(Paint.Align.CENTER);text.setTextSize(11);text.setColor(open?0xffffe08a:0xffd2d8df);c.drawText(open?"LIGHTBRIDGE OPEN":"LEARN FIRST",x,500,text);}}
    private void drawHome(Canvas c){float x=GameCore.HOME_X-cam;if(x<-230||x>viewW+230)return;p.setColor(0x66ffdc76);c.drawCircle(x,595,175,p);text.setTextAlign(Paint.Align.CENTER);text.setTextSize(25);text.setColor(0xffffdb72);c.drawText("EDEN COMMONS",x,470,text);for(int i=0;i<8;i++){float tx=x-120+i*34,ty=615+(i%2)*24;p.setColor(randColor());c.drawCircle(tx,ty-32,12,p);p.setColor(0xffe5c494);c.drawCircle(tx,ty-53,9,p);stroke.setColor(Color.WHITE);c.drawLine(tx,ty-20,tx,ty+15,stroke);}p.setColor(0xff9af2c4);c.drawRoundRect(x-112,688,x+112,736,18,18,p);text.setTextSize(16);text.setColor(0xff09242b);c.drawText("COME HOME ♥",x,718,text);}
    private void drawPlayer(Canvas c){float x=px-cam,y=py;p.setColor(0x5580fff0);c.drawCircle(x,y-43,50,p);p.setColor(0xff122c47);c.drawRoundRect(x-18,y-48,x+18,y+25,11,11,p);p.setColor(0xffddb18a);c.drawCircle(x,y-68,18,p);p.setColor(0xff80f2df);Path cloak=new Path();cloak.moveTo(x-18,y-43);cloak.lineTo(x-43,y+42);cloak.lineTo(x+43,y+42);cloak.lineTo(x+18,y-43);cloak.close();c.drawPath(cloak,p);p.setColor(0xffffda66);c.drawCircle(x+28,y-25,8,p);if(rainbow>0){int[] cs={0xffff73ad,0xffffd85c,0xff77eec1,0xff69baff,0xffc479ff};for(int i=0;i<5;i++){stroke.setColor(cs[i]);c.drawCircle(x,y-40,55+i*8,stroke);}}}

    private void drawHud(Canvas c){p.setColor(0xdd051525);c.drawRect(0,0,sw,88,p);text.setTextAlign(Paint.Align.LEFT);text.setTextSize(17);text.setColor(0xffffdb72);c.drawText("HOMEWARD",20,29,text);text.setTextSize(12);text.setColor(0xffa1f3e8);c.drawText("FORAGED "+core.getForageCount()+"   BREWS "+core.getCraftCount()+"/4   WIZARDS "+core.wizardCount()+"/5",20,54,text);text.setColor(Color.WHITE);c.drawText("FOLLOW THE GOLDEN ROAD HOME",20,75,text);float jx=96,jy=sh-95;stroke.setColor(0x99a2fff1);c.drawCircle(jx,jy,66,stroke);p.setColor(0x9975ded3);c.drawCircle(jx+sx*45,jy+sy*45,25,p);float ix=sw-95,iy=sh-95;p.setColor(0xdd187b88);c.drawCircle(ix,iy,63,p);text.setTextAlign(Paint.Align.CENTER);text.setTextSize(15);text.setColor(Color.WHITE);c.drawText(contextLabel(),ix,iy+5,text);String[] names={"BAG","AKHET","STEP","HAMSA","RAINBOW"};for(int i=0;i<5;i++){float x=sw*.5f-140+i*70,y=sh-62;p.setColor(0xaa1c3150);c.drawRoundRect(x-30,y-20,x+30,y+20,12,12,p);text.setTextSize(9);c.drawText(names[i],x,y+4,text);}}
    private void drawMessage(Canvas c){p.setColor(0xee061225);c.drawRoundRect(sw*.15f,sh*.12f,sw*.85f,sh*.28f,22,22,p);text.setTextAlign(Paint.Align.CENTER);text.setColor(0xffffda6d);text.setTextSize(14);c.drawText(speaker,sw/2,sh*.17f,text);text.setColor(Color.WHITE);text.setTextSize(17);c.drawText(message,sw/2,sh*.23f,text);}
    private void drawAlchemy(Canvas c){p.setColor(0xf4051021);c.drawRect(0,0,sw,sh,p);text.setTextAlign(Paint.Align.CENTER);text.setColor(0xffffda72);text.setTextSize(28);c.drawText("ATLANTEAN ALCHEMY",sw/2,88,text);for(int i=0;i<4;i++){float y=140+i*92;p.setColor(core.isCrafted(i)?0xff286e58:core.canCraft(i)?0xff176070:0xff283849);c.drawRoundRect(sw*.2f,y,sw*.8f,y+70,18,18,p);text.setColor(Color.WHITE);text.setTextSize(18);c.drawText(AlchemySystem.RECIPE_NAMES[i]+(core.isCrafted(i)?"  ✓":""),sw/2,y+30,text);text.setTextSize(12);text.setColor(0xffd5e9eb);c.drawText(AlchemySystem.RECIPE_DESC[i],sw/2,y+53,text);}text.setTextSize(12);text.setColor(Color.LTGRAY);c.drawText("Tap outside the recipes to return",sw/2,sh-40,text);}
    private void drawBag(Canvas c){p.setColor(0xf4051021);c.drawRect(0,0,sw,sh,p);text.setTextAlign(Paint.Align.CENTER);text.setColor(0xffffda72);text.setTextSize(28);c.drawText("TRAVELER SATCHEL",sw/2,90,text);for(int i=0;i<5;i++){float x=sw*.17f+i*sw*.165f;p.setColor(ingredientColor(i));c.drawCircle(x,190,28,p);text.setTextSize(12);text.setColor(Color.WHITE);c.drawText(Inventory.NAMES[i],x,235,text);text.setTextSize(20);c.drawText("× "+core.getIngredient(i),x,270,text);}text.setTextSize(13);c.drawText("Tap anywhere to return",sw/2,sh-50,text);}
    private void drawWin(Canvas c){p.setColor(0xf4050918);c.drawRect(0,0,sw,sh,p);text.setTextAlign(Paint.Align.CENTER);text.setColor(0xffffdc72);text.setTextSize(Math.min(70,sw*.065f));c.drawText("YOU'RE HOME.",sw/2,sh*.34f,text);text.setColor(Color.WHITE);text.setTextSize(Math.min(22,sw*.023f));c.drawText("THE TRIBE IS HERE. THE CAULDRON IS WARM. NEW ATLANTIS REMEMBERS.",sw/2,sh*.45f,text);text.setColor(0xff9af5df);text.setTextSize(16);c.drawText("FORAGED "+core.getForageCount()+" • BREWS 4 • WIZARDS 5",sw/2,sh*.55f,text);p.setColor(0xff187985);c.drawRoundRect(sw*.36f,sh*.66f,sw*.64f,sh*.79f,24,24,p);text.setColor(Color.WHITE);text.setTextSize(19);c.drawText("PLAY AGAIN",sw/2,sh*.74f,text);}

    private String contextLabel(){if(nearWizard(145)!=null)return "TALK";if(nearCauldron(145)!=null)return "BREW";if(nearResource(115)!=null)return "FORAGE";if(px>GameCore.HOME_X-170&&core.isWizardMet(4))return "HOME";return "NAVI";}
    private void interact(){WorldModel.WizardNode w=nearWizard(145);if(w!=null){talk(w);return;}if(nearCauldron(145)!=null){alchemy=true;return;}WorldModel.ResourceNode r=nearResource(115);if(r!=null){gather(r);return;}if(px>GameCore.HOME_X-170&&core.isWizardMet(4)){won=core.evaluateHome(GameCore.HOME_X);say("TRIBE","WELCOME HOME.",4);return;}say("NAVI","FOLLOW WHAT GLOWS. THE ROAD KEEPS OPENING EAST.",2);}
    private void gather(WorldModel.ResourceNode r){int n=hamsa>0?2:1;if(hamsa>0)hamsa--;core.gather(r.type,n);r.gathered=true;buzz(25);spawn(r.x,r.y,ingredientColor(r.type),14);say("NAVI","GATHERED "+Inventory.NAMES[r.type].toUpperCase()+" ×"+n,1.5f);}
    private void talk(WorldModel.WizardNode w){if(w.index<4&&!core.isCrafted(w.index)){say(w.name,"BRING ME "+AlchemySystem.RECIPE_NAMES[w.index]+" FROM A CAULDRON.",2.8f);return;}if(w.index==4&&core.getCraftCount()<4){say("THOTH","FOUR BREWS. FOUR LESSONS. THEN THE LAST ROAD HOME.",2.8f);return;}core.meetWizard(w.index);String[] gifts={"AKHET SIGHT AWAKENED.","PASSAGE STEP AWAKENED.","HAMSA BLESSING AWAKENED.","RAINBOW BODY AWAKENED.","THE MAP REMEMBERS YOU. GO HOME."};say(w.name,gifts[w.index],3);spawn(w.x,w.y-60,randColor(),28);}
    private void craft(int i){if(core.isCrafted(i)){say("ALCHEMY","THAT BREW IS ALREADY IN YOUR SATCHEL.",1.7f);return;}if(core.craft(i)){spawn(px,py-60,randColor(),30);say("ALCHEMY",AlchemySystem.RECIPE_NAMES[i]+" COMPLETE.",1.9f);}else say("ALCHEMY","FORAGE A LITTLE MORE. THE CAULDRON IS READY.",1.9f);}
    private void power(int i){if(i==0&&core.isWizardMet(0)){akhet=8;say("SPHINX","THE HORIZON REVEALS WHAT IS NEAR.",1.8f);}else if(i==1&&core.isWizardMet(1)){px=core.constrainX(px,px+420);say("ANUBIS","PASSAGE OPENS.",1.5f);}else if(i==2&&core.isWizardMet(2)){hamsa=3;say("HAMSA","THE NEXT THREE HARVESTS RETURN IN ABUNDANCE.",2);}else if(i==3&&core.isWizardMet(3)){rainbow=7;say("ORACLE","RAINBOW BODY: ALL ROADS BECOME MUSIC.",2);}else say("NAVI","THAT RUNE AWAKENS WITH A WIZARD LESSON.",1.5f);}
    private WorldModel.ResourceNode nearResource(float r){WorldModel.ResourceNode b=null;float best=r;for(WorldModel.ResourceNode n:world.resources){if(n.gathered)continue;float d=dist(px,py,n.x,n.y);if(d<best){best=d;b=n;}}return b;} private WorldModel.Cauldron nearCauldron(float r){WorldModel.Cauldron b=null;float best=r;for(WorldModel.Cauldron n:world.cauldrons){float d=dist(px,py,n.x,n.y);if(d<best){best=d;b=n;}}return b;} private WorldModel.WizardNode nearWizard(float r){WorldModel.WizardNode b=null;float best=r;for(WorldModel.WizardNode n:world.wizards){float d=dist(px,py,n.x,n.y);if(d<best){best=d;b=n;}}return b;}
    private float dist(float a,float b,float c,float d){float x=a-c,y=b-d;return(float)Math.sqrt(x*x+y*y);} private int ingredientColor(int i){return new int[]{0xff8ef5d0,0xff89c9ff,0xffdca1ff,0xffff9b69,0xffffdc62}[Math.max(0,Math.min(4,i))];} private int randColor(){return new int[]{0xffff72af,0xffffd95a,0xff78f0c4,0xff6cbaff,0xffc57cff}[rng.nextInt(5)];}
    private void spawn(float x,float y,int c,int count){for(int i=0;i<count;i++){double a=rng.nextDouble()*Math.PI*2;float v=30+rng.nextFloat()*95;sparks.add(new Spark(x,y,(float)Math.cos(a)*v,(float)Math.sin(a)*v,.5f+rng.nextFloat(),2+rng.nextFloat()*5,c));}} private void say(String s,String m,float t){speaker=s;message=m;msgT=t;} private void buzz(int ms){try{if(vib!=null){if(android.os.Build.VERSION.SDK_INT>=26)vib.vibrate(VibrationEffect.createOneShot(ms,70));else vib.vibrate(ms);}}catch(Exception ignored){}}

    @Override public boolean onTouchEvent(MotionEvent e){float x=e.getX(),y=e.getY();int a=e.getActionMasked(),idx=e.getActionIndex(),id=e.getPointerId(idx);if(title){if(a==MotionEvent.ACTION_DOWN){title=false;say("NAVI","ONE LEVEL. ONE INTENTION. GET HOME TO THE TRIBE.",3);}return true;}if(won){if(a==MotionEvent.ACTION_DOWN){core.reset();for(WorldModel.ResourceNode n:world.resources)n.gathered=false;px=GameCore.START_X;py=600;won=false;}return true;}if(alchemy){if(a==MotionEvent.ACTION_DOWN){for(int i=0;i<4;i++){float yy=140+i*92;if(y>=yy&&y<=yy+70&&x>=sw*.2f&&x<=sw*.8f){craft(i);return true;}}alchemy=false;}return true;}if(bag){if(a==MotionEvent.ACTION_DOWN)bag=false;return true;}if(a==MotionEvent.ACTION_DOWN||a==MotionEvent.ACTION_POINTER_DOWN){if(x<190&&y>sh-170&&stickId==-1){stickId=id;stick(x,y);return true;}if(x>sw-175&&y>sh-185){interact();return true;}float base=sw*.5f-140;for(int i=0;i<5;i++){float bx=base+i*70;if(Math.abs(x-bx)<34&&y>sh-100){if(i==0)bag=true;else power(i-1);return true;}}}if(a==MotionEvent.ACTION_MOVE){for(int i=0;i<e.getPointerCount();i++)if(e.getPointerId(i)==stickId)stick(e.getX(i),e.getY(i));return true;}if(a==MotionEvent.ACTION_UP||a==MotionEvent.ACTION_POINTER_UP||a==MotionEvent.ACTION_CANCEL){if(id==stickId){stickId=-1;sx=sy=0;}return true;}return true;}
    private void stick(float x,float y){float dx=x-96,dy=y-(sh-95),m=(float)Math.sqrt(dx*dx+dy*dy);if(m>66){dx=dx/m*66;dy=dy/m*66;}sx=dx/66;sy=dy/66;}
}
