plugins { id 'com.android.application' }

android {
    namespace 'com.ghostatlas.homeward'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ghostatlas.newatlantis.homeward'
        minSdk 23
        targetSdk 35
        versionCode 50031
        versionName '5.0.3-tier3-fix1'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
    }
}
